<?php

namespace Security\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MmUserSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MmUserSettingRepository extends EntityRepository
{
}
