WEBLOGS\MAIN\MTL\CodeMaintainanceBundle\Entity\VCodeMaintainance:
    type: entity
    table: v_code_maintainance
#    id:
#        dtindex:
#            type: string
#            nullable: false
#            length: 10
#            fixed: false
#            id: true
#            generator:
#            strategy: IDENTITY
    fields:
        ctk_customer_id:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: ctk_customer_id
        ctk_code:
            type: string
            nullable: false
            length: 100
            id: true
            fixed: false
            column: ctk_code
        task_name:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: task_name
        customer_name:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: customer_name
        ctk_budget_code:
            type: string
            nullable: false
            length: 100
            fixed: false   
            column: ctk_budget_code
        
    lifecycleCallbacks: {  }
