<?php
            
/*
    This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
    information. Thanks.
*/

namespace ESERV\MAIN\MembershipBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploymentDetailRepository extends EntityRepository
{   

    public function getPrimaryEmployerByContact($contact) {
        $query = $this->createQueryBuilder('a')
                        ->Where('a.contact = :c')
                        ->setParameter('c', $contact) 
                        ->andWhere('a.primaryRecord = :pr')
                        ->setParameter('pr', 'Y') 
                        ->andWhere('a.endDate IS NULL')
                        ->getQuery();   
        return $query->getOneOrNullResult();
    } 
    
}