<?php

namespace ESERV\MAIN\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentMasterAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentMasterAccessRepository extends EntityRepository
{
    public function getByDocumentMasterAndFosGroup($document_master, $fos_group) {
        $data = NULL;
        
        try {
            $query = $this->createQueryBuilder('u')                
                          ->where('u.documentMaster = :document_master_obj')
                          ->setParameter('document_master_obj', $document_master)
                          ->andWhere('u.fosGroup = :fos_group_obj')
                          ->setParameter('fos_group_obj', $fos_group);
            $data = $query->getQuery()
                          ->getOneOrNullResult();
        } catch (\Exception $ex) {
            $data = NULL;
            #var_dump($ex->getMessage()); die;
        }
                
        return $data;
    }    
}
