<?php

namespace ESERV\MAIN\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentMasterVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentMasterVersionRepository extends EntityRepository
{
}
