<?php

/*
    This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
    information. Thanks.
*/

namespace ESERV\MAIN\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchQueryRepository extends EntityRepository
{   
    public function createSearchQuery(
        $em
       ,$sql_query
       ,$result
    ) {
        $curr_date_time = new \DateTime();
        $activity = new \ESERV\MAIN\ActivityBundle\Entity\Activity();
        $search_query = new \ESERV\MAIN\ActivityBundle\Entity\SearchQuery();
        $search_query->setSqlQuery($sql_query);
        $search_query->setResult($result);
        $em->persist($search_query);
        $em->flush();        
        
        return $search_query;
    } #createSearchQuery end            
}