parameters:
#    eserv_home.example.class: ESERV\HomeBundle\Example

services:
#    eserv_home.example:
#        class: %eserv_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
