ESERV\MAIN\HelpersBundle\Entity\AltLanguageEntity: 
    type: entity
    repositoryClass: ESERV\MAIN\HelpersBundle\Entity\AltLanguageEntityRepository
    table: alt_language_entity
    indexes:
        fk_altlent_altlang_idx:
            columns:
                - alt_language_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entityName:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: entity_name
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        altLanguage:
            targetEntity: ESERV\MAIN\HelpersBundle\Entity\AltLanguage
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                alt_language_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
