ESERV\MAIN\HelpersBundle\Entity\AppText:
    type: entity
    repositoryClass: ESERV\MAIN\HelpersBundle\Entity\AppTextRepository
    table: app_text
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 100
            fixed: false
        name:
            type: string
            nullable: false
            length: 2000
            fixed: false
        location:
            type: string
            nullable: true
            length: 4000
            fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    lifecycleCallbacks: {  }
