<?php
            
/*
    This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
    information. Thanks.
*/

namespace ESERV\MAIN\CpdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CpdStatusDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CpdStatusDetailRepository extends EntityRepository
{ 
    
    public function getCpdStatusDetailByCpdStatusCode($cpdStatusCode)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $csd = $qb->select('csd')
                ->from('ESERVMAINCpdBundle:CpdStatusDetail', 'csd')
                ->leftJoin('csd.cpdStatus', 'cs')
                ->where('cs.code = :cs')
                ->setParameter('cs', $cpdStatusCode)
                ->orderBy('csd.displayOrder', 'ASC')
                ->getQuery()
                ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        return $csd;
    }

}