<?php
            
/*
    This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
    information. Thanks.
*/

namespace ESERV\MAIN\CpdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactCpdActDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactCpdActDocRepository extends EntityRepository
{   
    public function isContactCpdDocLibInOtherContactCpdActDoc($contactCpdDocLib, $contactCpdActDoc)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $result = $qb->select('ccad')
                ->from('ESERVMAINCpdBundle:ContactCpdActDoc', 'ccad')
                ->leftJoin('ccad.contactCpdDocLib', 'ccdl')
                ->where('ccdl.id = :dlId')
                ->setParameter('dlId', $contactCpdDocLib)
                ->andWhere('ccad.id NOT IN (:adId)')
                ->setParameter('adId', $contactCpdActDoc)
                ->getQuery()
                ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        if(count($result)>0){
            return true;
        } else {
            return false;
        }
    }
}