parameters:
#    eserv_help_bundle_components_knowledge_base.example.class: ESERV\HelpBundle\Components\KnowledgeBaseBundle\Example

services:
#    eserv_help_bundle_components_knowledge_base.example:
#        class: %eserv_help_bundle_components_knowledge_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
