parameters:
#    eservmain_administration_bundle_components_client_administration.example.class: ESERV\MAIN\AdministrationBundle\Components\ClientAdministrationBundle\Example

services:
#    eservmain_administration_bundle_components_client_administration.example:
#        class: %eservmain_administration_bundle_components_client_administration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    client_admin_bundle_services:
        class: ESERV\MAIN\AdministrationBundle\Components\ClientAdministrationBundle\Services\ESERVMAINAdminClientServices
        arguments: ["@doctrine.orm.entity_manager","@service_container","@core_function_services","@db_core_function_services"]