<?php

namespace ESERV\MAIN\SystemConfigBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EservSaveQueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EservSaveQueryRepository extends EntityRepository
{
}
