ESERV\TestBundle\Entity\GtcwVSubject: 
    type: entity
    table: gtcw_v_subject
    id:
        subject_id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        qualType:
            type: string
            column: qual_type
            nullable: false
            length: 100
            fixed: false
            comment: ''
        dateOpened:
            type: datetime
            nullable: false
            comment: ''
            column: date_opened
        dateClosed:
            type: datetime
            nullable: true
            comment: ''
            column: date_closed        