# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: weblogs_home_homepage
                always_use_default_target_path: true
                success_handler: eserv.security.authentication_handler
                failure_handler: eserv.security.authentication_handler
            logout:       true
            anonymous:    true
            entry_point: authentication_entry_point
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/save_to_fos, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ws/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/soap/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/r/a/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/p/a/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, role: [ROLE_USER] }
