ESERV\MAIN\ProductBundle\Entity\ProductType: 
    type: entity
    repositoryClass: ESERV\MAIN\ProductBundle\Entity\ProductTypeRepository
    table: product_type
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 10
            fixed: false
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    lifecycleCallbacks: {  }
