ESERV\MAIN\ProductBundle\Entity\Transaction: 
    type: entity
    repositoryClass: ESERV\MAIN\ProductBundle\Entity\TransactionRepository
    table: transaction
    indexes:
        fk_transa_contac_idx:
            columns:
                - contact_id
        fk_transa_traori_idx:
            columns:
                - transaction_origin_id
        fk_transa_paymet_idx:
            columns:
                - payment_method_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        credit:
            type: float
            nullable: false
            precision: 10
            scale: 0
        debit:
            type: float
            nullable: false
            precision: 10
            scale: 0
        dateProcessed:
            type: datetime
            nullable: true
            column: date_processed
        comments:
            type: string
            nullable: true
            length: 255
            fixed: false
        extCardPaymentRef:
            type: string
            nullable: true
            length: 50
            column: ext_card_payment_ref
        intCardPaymentRef:
            type: string
            nullable: true
            length: 50
            column: int_card_payment_ref    
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        contact:
            targetEntity: ESERV\MAIN\ContactBundle\Entity\Contact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        transactionOrigin:
            targetEntity: ESERV\MAIN\SystemConfigBundle\Entity\TransactionOrigin
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                transaction_origin_id:
                    referencedColumnName: id
            orphanRemoval: false
        paymentMethod:
            targetEntity: ESERV\MAIN\SystemConfigBundle\Entity\PaymentMethod
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                payment_method_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
