ESERV\MAIN\ProductBundle\Entity\VatRate: 
    type: entity
    repositoryClass: ESERV\MAIN\ProductBundle\Entity\VatRateRepository
    table: vat_rate
    indexes:
        fk_vat_rate_vat1_idx:
            columns:
                - vat_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        startDate:
            type: datetime
            nullable: false
            column: start_date
        endDate:
            type: datetime
            nullable: true
            column: end_date
        amount:
            type: float
            nullable: false
            precision: 8
            scale: 2
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        vat:
            targetEntity: ESERV\MAIN\ProductBundle\Entity\Vat
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                vat_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
