<?php
            
/*
    This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
    information. Thanks.
*/

namespace ESERV\MAIN\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MmUserSettingOrgRepository extends EntityRepository
{   

    public function getByOrgContactId($org_contact_id, $mus_contact_id) {
        $result = array();

        try {
            $result = $this->createQueryBuilder('mo')
                           #->select('p.referenceNo, p.initials, p.firstName, p.lastName, p.dateOfBirth, p.gender')
                           ->innerJoin('mo.orgContact', 'co')
                           ->innerJoin('mo.mmUserSetting', 'mus')
                           ->innerJoin('mus.contact', 'cm')
                           ->innerJoin('mus.fosUser', 'u')
                           ->where('co.id = :orgContactId')
                           ->setParameter('orgContactId', $org_contact_id)
                           ->andWhere('cm.id = :mosContactId')
                           ->setParameter('mosContactId', $mus_contact_id)
                           ->getQuery()
                           ->getOneOrNullResult()
                    ;
        } catch (\Exception $ex) {
            $result = array();
            #var_dump($ex->getMessage()); die;
        }

        return $result;
    } #getByOrgContactId
    
    
}