ESERV\MAIN\ContactBundle\Entity\ContactCustom:
    type: entity
    table: contact_custom
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        contact_id:
            type: integer
            length: 11
        text_a:
            type: string
        external_id:
            type: string
        created_at:
            type: datetime
        updated_at:
            type: datetime
        created_by:
            type: bigint
        updated_by:
            type: bigint
    uniqueConstraints:
       idx_ContactCustom_a_idx: 
           columns: [ contact_id  ]              
    manyToOne:
        contact:
            targetEntity: Contact
            inversedBy: contact_custom
            joinColumn:
                name: contact_id
                referencedColumnName: id