ESERV\MAIN\ContactBundle\Entity\ContactJobFunction:
    type: entity
    table: contact_job_function
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        contact_id:
            type: integer
            length: 11
        job_function_id:
            type: integer
            length: 11
        external_id:
            type: string
        created_at:
            type: datetime
        updated_at:
            type: datetime
        created_by:
            type: bigint
        updated_by:
            type: bigint
    uniqueConstraints:
       idx_ContactJobFunct_a_idx: 
           columns: [ contact_id  ]
       idx_ContactJobFunct_b_idx: 
           columns: [ job_function_id  ]    
    manyToOne:
        contact:
            targetEntity: Contact
            inversedBy: contact_job_function
            joinColumn:
                name: contact_id
                referencedColumnName: id