ESERV\MAIN\ContactBundle\Entity\ContactDisciplinary: 
    type: entity
    repositoryClass: ESERV\MAIN\ContactBundle\Entity\ContactDisciplinaryRepository
    table: contact_disciplinary
    indexes:
        fk_contact_disciplinary_contact1_idx:
            columns:
                - contact_id
        fk_contact_disciplinary_application_code1_idx:
            columns:
                - disc_type_id
        fk_contact_disciplinary_system_code1_idx:
            columns:
                - web_enabled_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        disciplinaryNote:
            type: text
            nullable: true
            length: 65535
            fixed: false
            column: disciplinary_note
        startDate:
            type: datetime
            nullable: true
            column: start_date
        endDate:
            type: datetime
            nullable: true
            column: end_date
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        contact:
            targetEntity: ESERV\MAIN\ContactBundle\Entity\Contact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        discType:
            targetEntity: ESERV\MAIN\ApplicationCodeBundle\Entity\ApplicationCode
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                disc_type_id:
                    referencedColumnName: id
            orphanRemoval: false
        webEnabled:
            targetEntity: ESERV\MAIN\SystemConfigBundle\Entity\SystemCode
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                web_enabled_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
