ESERV\MAIN\ContactBundle\Entity\PersonEmployment:
    type: entity
    table: person_employment
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        contact_id:
            type: integer
            length: 4
        external_id:
            type: string            
        created_at:
            type: datetime
        updated_at:
            type: datetime
        created_by:
            type: bigint
        updated_by:
            type: bigint