ESERV\MAIN\ContactBundle\Entity\Person: 
    type: entity
    repositoryClass: ESERV\MAIN\ContactBundle\Entity\PersonRepository
    table: person
    indexes:
        IDX_34DCD176E7A1254A:
            columns:
                - contact_id
        fk_person_application_code2_idx:
            columns:
                - nationality_id
        fk_person_application_code3_idx:
            columns:
                - national_iden_id
        fk_person_application_code4_idx:
            columns:
                - ethnic_group_id
        fk_person_title_idx:
            columns:
                - title_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: first_name
        middleName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: middle_name
        lastName:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: last_name
        lastNameSearch:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: last_name_search
        initials:
            type: string
            nullable: true
            length: 20
            fixed: false
        dateOfBirth:
            type: datetime
            nullable: true
            column: date_of_birth
        jobTitle:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: job_title
        gender:
            type: string
            nullable: true
            length: 1
            fixed: false
            comment: 'M-Male, F-Female'
        previousLastName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: previous_last_name
        referenceNo:
            type: string
            nullable: true
            length: 30
            fixed: false
            column: reference_no
        disabled:
            type: string
            nullable: true
            length: 1
            fixed: false
            default: N
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
        niNumber:
            type: string
            nullable: true
            length: 30
            fixed: false
            column: ni_number
    manyToOne:
        contact:
            targetEntity: ESERV\MAIN\ContactBundle\Entity\Contact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        title:
            targetEntity: ESERV\MAIN\SystemConfigBundle\Entity\Title
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                title_id:
                    referencedColumnName: id
            orphanRemoval: false
        nationality:
            targetEntity: ESERV\MAIN\ApplicationCodeBundle\Entity\ApplicationCode
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                nationality_id:
                    referencedColumnName: id
            orphanRemoval: false
        nationalen:
            targetEntity: ESERV\MAIN\ApplicationCodeBundle\Entity\ApplicationCode
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                national_iden_id:
                    referencedColumnName: id
            orphanRemoval: false
        ethnicGroup:
            targetEntity: ESERV\MAIN\ApplicationCodeBundle\Entity\ApplicationCode
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ethnic_group_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
