<?php

namespace ESERV\MAIN\WizardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WzControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WzControlRepository extends EntityRepository
{
}
