ESERV\MAIN\CpdBundle\Entity\ContactCpdStatusDetail: 
    type: entity
    repositoryClass: ESERV\MAIN\CpdBundle\Entity\ContactCpdStatusDetailRepository
    table: contact_cpd_status_detail
    indexes:
        fk_ccpdsd_cocpst_idx:
            columns:
                - contact_cpd_status_id
        fk_ccpdsd_cpstde_idx:
            columns:
                - cpd_status_detail_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        conCpdStatusText:
            type: text
            nullable: true
            length: 65535
            fixed: false
            column: con_cpd_status_text
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        contactCpdStatus:
            targetEntity: ESERV\MAIN\CpdBundle\Entity\ContactCpdStatus
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_cpd_status_id:
                    referencedColumnName: id
            orphanRemoval: false
        cpdStatusDetail:
            targetEntity: ESERV\MAIN\CpdBundle\Entity\CpdStatusDetail
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cpd_status_detail_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
