ESERV\MAIN\CpdBundle\Entity\CpdActTypeDetail: 
    type: entity
    repositoryClass: ESERV\MAIN\CpdBundle\Entity\CpdActTypeDetailRepository
    table: cpd_act_type_detail
    indexes:
        fk_cpdatd_cptact_idx:
            columns:
                - cpd_act_type_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 10
            fixed: false
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
        displayOrder:
            type: integer
            nullable: false
            unsigned: false
            column: display_order
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        cpdActType:
            targetEntity: ESERV\MAIN\CpdBundle\Entity\CpdActType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cpd_act_type_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
