<?php
            
/*
    This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
    information. Thanks.
*/

namespace ESERV\MAIN\MembershipBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContRateMasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContRateMasterRepository extends EntityRepository
{   

    public function getByCodeAndMembershipOrg($code, $memberOrgCode) {
        $crm = NULL;
        
        try {
            $crm = $this->createQueryBuilder('c')
                        ->join('c.membershipOrg', 'mo')
                        ->where('c.code = :in_code')
                        ->setParameter('in_code', $code)
                        ->andWhere('mo.code = :cd')
                        ->setParameter('cd', $memberOrgCode)
                        ->getQuery()
                        ->getOneOrNullResult();
        } catch (\Exception $e) {
            $crm = NULL;
        }
      
        return $crm;
    }
    
}