<?php
            
        /*
            This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
            information. Thanks.
        */

        namespace ESERV\MAIN\MembershipBundle\Entity;

        use Doctrine\ORM\EntityRepository;

        /**
         * MemberHistRepository
         *
         * This class was generated by the Doctrine ORM. Add your own custom
         * repository methods below.
         */
        class MemberHistRepository extends EntityRepository
        {   

        }