<?php
            
/*
    This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
    information. Thanks.
*/

namespace ESERV\MAIN\MembershipBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRateRepository extends EntityRepository
{   

    public function geByMemberId($member, $include_closed = FALSE) {
        $rec_arr = array();
        try {
            $q = $this->createQueryBuilder('m')
                      ->where('m.member = :memberObj')
                      ->setParameter('memberObj', $member);
            if (!($include_closed)) {
                $q->andWhere('m.endDate IS NULL');
            }            
            $rec_arr = $q->getQuery()
                         ->getResult(); 
        } catch (\Exception $ex) {
            $rec_arr = array();
        }

        return $rec_arr;
    }

}