<?php
            
/*
    This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
    information. Thanks.
*/

namespace ESERV\MAIN\MembershipBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberSubjectRepository extends EntityRepository
{   

    public function canMemberAddMoreSubjects($memberId) {
        $qb = $this->createQueryBuilder('ms');
        $result = $qb->select('ms')
//                ->from('ESERVMAINMembershipBundle:MemberSubject', 'ms')
                ->leftJoin('ESERVMAINMembershipBundle:MemberSubjectTaught', 'mst', 'WITH', '( mst.memberSubject = ms.id and mst.member =' . $memberId . ')')
                ->leftJoin('ESERVMAINMembershipBundle:MembershipOrg', 'mo', 'WITH', 'mo.id = ms.membershipOrg')
                ->where('ms.dateClosed IS NULL')
                ->andWhere('mst.id is NULL')
                ->andWhere('mo.code = :cd')
                ->setParameter('cd', \ESERV\MAIN\Services\AppConstants::MEMBERSHIP_ORG_REG)
                ->getQuery()
                ->getResult()
        ;
        if (count($result) > 0) {
            return true;
        }
        return false;
    }
    
}