<?php

namespace ESERV\MAIN\ErrorHandlingBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ESERV\MAIN\Services\AppConstants;

/**
 * MtlErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MtlErrorRepository extends EntityRepository
{     

}