<?php

namespace ESERV\MAIN\WizardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WzPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WzPageRepository extends EntityRepository
{
}
