<?php

namespace Security\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EservVUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EservVUserRepository extends EntityRepository
{
}
