ESERV\MAIN\TableQueryBundle\Entity\QueryViewLov:
    type: entity
    table: query_view_lov
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tableName:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: 'table_name can be name of the view as well.'
            column: table_name
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
        isActive:
            type: integer
            nullable: false
            unsigned: false
            column: is_active
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    lifecycleCallbacks: {  }
