ESERV\MAIN\TableQueryBundle\Entity\QueryDetailWhere:
    type: entity
    table: query_detail_where
    indexes:
        fk_qdewhe_quview_idx:
            columns:
                - query_master_id
        fk_qdewhe_qviewf_idx:
            columns:
                - query_view_field_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lineNo:
            type: integer
            nullable: false
            unsigned: false
            column: line_no
        qdetJoin:
            type: string
            nullable: false
            length: 30
            fixed: false
            column: qdet_join
        qdetExpression:
            type: string
            nullable: false
            length: 30
            fixed: false
            column: qdet_expression
        qdetValue1:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: qdet_value1
        qdetValue2:
            type: string
            nullable: true
            length: 100
            fixed: false
            column: qdet_value2
        qdetOpenBracket:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: qdet_open_bracket
        qdetCloseBracket:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: qdet_close_bracket
        promptForValue:
            type: string
            nullable: false
            length: 1
            fixed: false
            default: N
            column: prompt_for_value
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        queryMaster:
            targetEntity: ESERV\MAIN\TableQueryBundle\Entity\QueryMaster
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                query_master_id:
                    referencedColumnName: id
            orphanRemoval: false
        queryViewField:
            targetEntity: ESERV\MAIN\TableQueryBundle\Entity\QueryViewField
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                query_view_field_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
