ESERV\MAIN\MembershipBundle\Entity\ContRateMaster: 
    type: entity
    repositoryClass: ESERV\MAIN\MembershipBundle\Entity\ContRateMasterRepository
    table: cont_rate_master
    indexes:
        fk_cont_rate_master_membership_org1_idx:
            columns:
                - membership_org_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 10
            fixed: false
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
        dateOpened:
            type: datetime
            nullable: false
            column: date_opened
        dateClosed:
            type: datetime
            nullable: true
            column: date_closed
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        membershipOrg:
            targetEntity: ESERV\MAIN\MembershipBundle\Entity\MembershipOrg
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                membership_org_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
