ESERV\MAIN\MembershipBundle\Entity\MemberRate: 
    type: entity
    repositoryClass: ESERV\MAIN\MembershipBundle\Entity\MemberRateRepository
    table: member_rate
    indexes:
        fk_member_rate_member1_idx:
            columns:
                - member_id
        fk_member_rate_fund1_idx:
            columns:
                - fund_id
        fk_member_rate_frequency1_idx:
            columns:
                - frequency_id
        fk_member_rate_cont_rate_master1_idx:
            columns:
                - cont_rate_master_id
        fk_member_rate_payment_method1_idx:
            columns:
                - payment_method_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        startDate:
            type: datetime
            nullable: false
            column: start_date
        endDate:
            type: datetime
            nullable: true
            column: end_date
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        member:
            targetEntity: ESERV\MAIN\MembershipBundle\Entity\Member
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                member_id:
                    referencedColumnName: id
            orphanRemoval: false
        fund:
            targetEntity: ESERV\MAIN\SystemConfigBundle\Entity\Fund
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fund_id:
                    referencedColumnName: id
            orphanRemoval: false
        frequency:
            targetEntity: ESERV\MAIN\SystemConfigBundle\Entity\Frequency
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                frequency_id:
                    referencedColumnName: id
            orphanRemoval: false
        contRateMaster:
            targetEntity: ESERV\MAIN\MembershipBundle\Entity\ContRateMaster
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cont_rate_master_id:
                    referencedColumnName: id
            orphanRemoval: false
        paymentMethod:
            targetEntity: ESERV\MAIN\SystemConfigBundle\Entity\PaymentMethod
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                payment_method_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
