<?php

namespace WEBLOGS\CORE\MAIN\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MmUserSettingOrgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MmUserSettingOrgRepository extends EntityRepository
{
}
