parameters:
#    eservcore_product.example.class: ESERV\MAIN\ProductBundle\Example

services:
#    eservcore_product.example:
#        class: %eservcore_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
