<?php
            
        /*
            This file has been generated using MTL ESERV:BUILD command.
        */

        namespace ESERV\MAIN\SystemConfigBundle\Entity;

        use Doctrine\ORM\EntityRepository;

        /**
         * ActivityRepository
         *
         * This class was generated by the Doctrine ORM. Add your own custom
         * repository methods below.
         */
        class SystemConfigRepository extends EntityRepository
        {   
            public function getSystemConfigValues($type = 'array', $options = array()) {        
                $result = '';
                $query = $this->getEntityManager()
                              ->createQueryBuilder('s')
                              ->select('s')
                              ->from('ESERVMAINSystemConfigBundle:SystemConfig', 's')
                              ->getQuery();
                
                if('array' == $type){
                    $result = $query->getArrayResult();
                }                

                return $result;
            }
            
            public function getFormattedSystemConfigValues()
            {
                $data = $this->getSystemConfigValues('array');
                $array = array();
                
                foreach($data as $k => $v){
                    if(isset($v['code'])){
                        $array[$v['code']] = array(
                            'name' => $v['name'], 
                            'configValue' => $v['configValue']
                        );
                    }
                }
                
                return $array;
            }
            
            public function updateSystemConfigValueByCode($code, $value)
            {
                $status = false;
                $msg = '';
                try{
                    $sysConfig = $this->getEntityManager()
                                ->getRepository('ESERVMAINSystemConfigBundle:SystemConfig')
                                ->findOneBy(array('code' => $code));
                    
                    if($sysConfig){
                        if (!is_null($value)) {
                            $sysConfig->setConfigValue($value);
                            $status = true;
                        }                        
                    }else{
                        $status = false;
                    }
                }catch(\Exception $e){
                    $status = false;
                    $msg = $e->getMessage();
                }
                
                $result = array(
                    'success' => $status,
                    'msg' => $msg,
                );
                
                return $result;
            }
        }