<?php
            
        /*
            This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
            information. Thanks.
        */

        namespace ESERV\MAIN\ContactBundle\Entity;

        use Doctrine\ORM\EntityRepository;

        /**
         * ActivityRepository
         *
         * This class was generated by the Doctrine ORM. Add your own custom
         * repository methods below.
         */
        class ContactStatusRepository extends EntityRepository
        {   
            public function getOneByCodeAndContactStatus($contact_status_code, $contact_type_code) {
                $result = $this->createQueryBuilder('cs')
                               ->leftJoin('cs.contactType', 'ct')
                               ->where('cs.code = :cs_code')
                               ->setParameter('cs_code', $contact_status_code)
                               ->andWhere('ct.code = :ct_code')
                               ->setParameter('ct_code', $contact_type_code)                            
                               ->getQuery()
                               ->getSingleResult();
                return $result;
            } #getOneByCodeAndContactStatus end
        }