<?php

namespace ESERV\MAIN\SystemConfigBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ESERV\MAIN\Services\AppConstants;

/**
 * SystemCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemCodeRepository extends EntityRepository
{     
    public function getBySystemCodeTypeAndCode($system_code_type, $code, $col = 'ALL') {        
        if ($col === 'ALL') {
            $query = $this->createQueryBuilder('s')
                          ->leftJoin('s.systemCodeType', 't')
                          ->where('t.code = :system_code_type')
                          ->andWhere('s.code = :code')
                          ->setParameter('system_code_type', $system_code_type)
                          ->setParameter('code', $code)
                          ->getQuery();
            $result = $query->getOneOrNullResult();
        } else {
            if (is_array($col)) {
                $col_arr = $col;
            } else {
                $col_arr = array($col);
            }
            $select_col = '';
            foreach($col_arr as $key => $value) {
              $select_col = $select_col . 's.' . $value . ',';
            }
            $select_col = rtrim($select_col, ',');
            $query = $this->createQueryBuilder('s')
                          ->select($select_col)
                          ->leftJoin('s.systemCodeType', 't')
                          ->where('t.code = :system_code_type')
                          ->andWhere('s.code = :code')
                          ->setParameter('system_code_type', $system_code_type)
                          ->setParameter('code', $code)
                          ->getQuery();
            $result = $query->getOneOrNullResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        }        
        
        return $result;
    }

    public function getActivityCompleteStatus($col = 'ALL') {
        $sys_code = self::getBySystemCodeTypeAndCode(
                        AppConstants::SCT_ACTIVITY_STATUS_CODE
                       ,AppConstants::SC_ACTIVITY_STATUS_COMPLETE_CODE
                       ,$col
                    );
        return $sys_code;
    }
    
    public function getActivityOutstandingStatus() {
        $sys_code = self::getBySystemCodeTypeAndCode(
                        AppConstants::SCT_ACTIVITY_STATUS_CODE
                       ,AppConstants::SC_ACTIVITY_STATUS_OUTSTANDING_CODE
                    );
        return $sys_code;
    }    
    
    public function getActivityQueuedSendingStatus($code = 'ALL') {
        $sys_code = self::getBySystemCodeTypeAndCode(
                        AppConstants::SCT_ACTIVITY_EMAIL_STATUS_CODE
                       ,AppConstants::SC_ACTIVITY_EMAIL_STATUS_QUEUED_CODE
                       ,$code
                    );
        return $sys_code;
    }
    
    public function getActivityEmailSendingStatus($code = 'ALL') {
        $sys_code = self::getBySystemCodeTypeAndCode(
                        AppConstants::SCT_ACTIVITY_EMAIL_STATUS_CODE
                       ,AppConstants::SC_ACTIVITY_EMAIL_STATUS_SENDING_CODE
                       ,$code
                    );
        return $sys_code;
    }
    
    public function getActivityEmailSentStatus($code = 'ALL') {
        $sys_code = self::getBySystemCodeTypeAndCode(
                        AppConstants::SCT_ACTIVITY_EMAIL_STATUS_CODE
                       ,AppConstants::SC_ACTIVITY_EMAIL_STATUS_SENT_CODE
                       ,$code
                    );
        return $sys_code;
    }
    
    public function getNotificationStatus($code = 'ALL') {
        $sys_code = self::getBySystemCodeTypeAndCode(
                        AppConstants::SCT_NOTIFICATION_PRIORITY
                       ,$code
                    );
        return $sys_code;
    }
}
