<?php

namespace ESERV\ConsoleCommandBundle\Services;

class FileNameDefinition
{

    protected $file_names_array;

    function __construct()
    {
        $this->file_names_array = array(
            array('name' => 'ActivityCategory', 
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            array('name' => 'Activity', 
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            array('name' => 'ActivityAssignment', 
                  'location' => 'ESERV/MAIN/ActivityBundle/'),           
            array('name' => 'ActivityComment', 
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            array('name' => 'ActivityEmail',
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            array('name' => 'ActivityJob',
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            array('name' => 'ActivityLink',
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            array('name' => 'ActivitySet',
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            array('name' => 'ActivitySubCategory',
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            array('name' => 'ActivityTarget',
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            array('name' => 'ActivityType',
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            array('name' => 'ActivityMergeData',
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            array('name' => 'SearchQuery',
                  'location' => 'ESERV/MAIN/ActivityBundle/'),
            
            array('name' => 'ApplicationCode', 
                  'location' => 'ESERV/MAIN/ApplicationCodeBundle/'),
            array('name' => 'ApplicationCodeType', 
                  'location' => 'ESERV/MAIN/ApplicationCodeBundle/'),            
            
            array('name' => 'DocumentJob', 
                  'location' => 'ESERV/MAIN/CommunicationsBundle/'),
            array('name' => 'DocumentQueue', 
                  'location' => 'ESERV/MAIN/CommunicationsBundle/'),
            array('name' => 'EmailMergingArchive', 
                  'location' => 'ESERV/MAIN/CommunicationsBundle/'),
            array('name' => 'EmailMergingLookupArchive', 
                  'location' => 'ESERV/MAIN/CommunicationsBundle/'),  
            
            array('name' => 'Address',
                  'location' => 'ESERV/MAIN/ContactBundle/Components/ContactDetailsBundle/'), 
            array('name' => 'AddressHistory',
                  'location' => 'ESERV/MAIN/ContactBundle/Components/ContactDetailsBundle/'), 
            array('name' => 'AddressType', 
                  'location' => 'ESERV/MAIN/ContactBundle/Components/ContactDetailsBundle/'),
            array('name' => 'Email',
                  'location' => 'ESERV/MAIN/ContactBundle/Components/ContactDetailsBundle/'), 
            array('name' => 'Phone',
                  'location' => 'ESERV/MAIN/ContactBundle/Components/ContactDetailsBundle/'), 
            array('name' => 'Website', 
                  'location' => 'ESERV/MAIN/ContactBundle/Components/ContactDetailsBundle/'),
            
            array('name' => 'Contact',
                  'location' => 'ESERV/MAIN/ContactBundle/'), 
            array('name' => 'ContactStatus',
                  'location' => 'ESERV/MAIN/ContactBundle/'),
            array('name' => 'ContactSubtype',
                  'location' => 'ESERV/MAIN/ContactBundle/'),
            array('name' => 'ContactSubtypeList',
                  'location' => 'ESERV/MAIN/ContactBundle/'),
            array('name' => 'ContactTag',
                  'location' => 'ESERV/MAIN/ContactBundle/'),
            array('name' => 'ContactTagType',
                  'location' => 'ESERV/MAIN/ContactBundle/'),
            array('name' => 'ContactType',
                  'location' => 'ESERV/MAIN/ContactBundle/'),
            array('name' => 'ContactUnavailable',
                  'location' => 'ESERV/MAIN/ContactBundle/'),
            array('name' => 'Organisation',
                  'location' => 'ESERV/MAIN/ContactBundle/'),            
            array('name' => 'Person',
                  'location' => 'ESERV/MAIN/ContactBundle/'),
            array('name' => 'Relationship',
                  'location' => 'ESERV/MAIN/ContactBundle/'),
            array('name' => 'RelationshipType',
                  'location' => 'ESERV/MAIN/ContactBundle/'),
            array('name' => 'ContactDisciplinary',
                  'location' => 'ESERV/MAIN/ContactBundle/'),
                        
            array('name' => 'MtlError',
                  'location' => 'ESERV/MAIN/ErrorHandlingBundle/'),
            
            array('name' => 'QueuedDbProcess',
                  'location' => 'ESERV/MAIN/ExternalBundle/'),
            array('name' => 'QueuedDbProcessVar',
                  'location' => 'ESERV/MAIN/ExternalBundle/'),            

            array('name' => 'PageRecordLastViewed',
                  'location' => 'ESERV/MAIN/HistoryBundle/'),
            array('name' => 'UserBrowsingHistory',
                  'location' => 'ESERV/MAIN/HistoryBundle/'),
            array('name' => 'MtlAudit',
                  'location' => 'ESERV/MAIN/HistoryBundle/'),
            array('name' => 'MtlDeletedRecord',
                  'location' => 'ESERV/MAIN/HistoryBundle/'),
            array('name' => 'History',
                  'location' => 'ESERV/MAIN/HistoryBundle/'),
            array('name' => 'HistoryControl',
                  'location' => 'ESERV/MAIN/HistoryBundle/'),
            
            array('name' => 'MediaStore',
                  'location' => 'ESERV/MAIN/MediaBundle/'),
            array('name' => 'MediaStoreHistory',
                  'location' => 'ESERV/MAIN/MediaBundle/'),
            array('name' => 'MediaStoreStaging',
                  'location' => 'ESERV/MAIN/MediaBundle/'),
            array('name' => 'MediaType',
                  'location' => 'ESERV/MAIN/MediaBundle/'),
            
            array('name' => 'Invoice',
                  'location' => 'ESERV/MAIN/ProductBundle/'),
            array('name' => 'InvoiceDetail',
                  'location' => 'ESERV/MAIN/ProductBundle/'),
            array('name' => 'Product',
                  'location' => 'ESERV/MAIN/ProductBundle/'),
            array('name' => 'ProductPrice',
                  'location' => 'ESERV/MAIN/ProductBundle/'),
            array('name' => 'ProductStockAdjustment',
                  'location' => 'ESERV/MAIN/ProductBundle/'),
            array('name' => 'ProductType',
                  'location' => 'ESERV/MAIN/ProductBundle/'),
            array('name' => 'Vat',
                  'location' => 'ESERV/MAIN/ProductBundle/'),
            array('name' => 'VatRate',
                  'location' => 'ESERV/MAIN/ProductBundle/'),
            array('name' => 'Transaction',
                  'location' => 'ESERV/MAIN/ProductBundle/'),
            array('name' => 'TransactionDetail',
                  'location' => 'ESERV/MAIN/ProductBundle/'),
            
            array('name' => 'MmHelpMessage',
                  'location' => 'ESERV/MAIN/ProfileBundle/'),
            array('name' => 'MmNews',
                  'location' => 'ESERV/MAIN/ProfileBundle/'),
            array('name' => 'MmNewsUserProfile',
                  'location' => 'ESERV/MAIN/ProfileBundle/'),
            array('name' => 'MmUserProfile',
                  'location' => 'ESERV/MAIN/ProfileBundle/'),
            array('name' => 'MmUserSetting',
                  'location' => 'ESERV/MAIN/ProfileBundle/'),
            array('name' => 'UserLockedPage',
                  'location' => 'ESERV/MAIN/ProfileBundle/'),
            array('name' => 'UserNotification',
                  'location' => 'ESERV/MAIN/ProfileBundle/'),
            array('name' => 'UserNotificationStatus',
                  'location' => 'ESERV/MAIN/ProfileBundle/'),
            array('name' => 'UserDepartment',
                  'location' => 'ESERV/MAIN/ProfileBundle/'),
            array('name' => 'MmUserSettingOrg',
                  'location' => 'ESERV/MAIN/ProfileBundle/'),
            
            array('name' => 'Country',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'Language',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'SystemCode',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'SystemCodeType',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'SystemConfig',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'SystemPrinter',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'MtlModule',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'MtlColour',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'Frequency',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'PaymentMethod',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'Fund',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'Title',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'AppConfigFlag',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'DocumentSet',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'DocumentSetList',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'Colour',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'TransactionType',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            array('name' => 'TransactionOrigin',
                  'location' => 'ESERV/MAIN/SystemConfigBundle/'),
            
            array('name' => 'Template',
                  'location' => 'ESERV/MAIN/TemplateBundle/'),
            array('name' => 'MailMergeTypeField',
                  'location' => 'ESERV/MAIN/TemplateBundle/'),
            array('name' => 'MailMergeType',
                  'location' => 'ESERV/MAIN/TemplateBundle/'),
            array('name' => 'MailMergeField',
                  'location' => 'ESERV/MAIN/TemplateBundle/'),
            array('name' => 'MailMergeFieldType',
                  'location' => 'ESERV/MAIN/TemplateBundle/'),
            array('name' => 'TemplateType',
                  'location' => 'ESERV/MAIN/TemplateBundle/'),
            array('name' => 'TemplateVersion',
                  'location' => 'ESERV/MAIN/TemplateBundle/'),          
            
            array('name' => 'WizardType',
                  'location' => 'ESERV/MAIN/WizardBundle/'),
            array('name' => 'WzControl',
                  'location' => 'ESERV/MAIN/WizardBundle/'),
            array('name' => 'WzPageFive',
                  'location' => 'ESERV/MAIN/WizardBundle/'),
            array('name' => 'WzPageFour',
                  'location' => 'ESERV/MAIN/WizardBundle/'),
            array('name' => 'WzPageOne',
                  'location' => 'ESERV/MAIN/WizardBundle/'),
            array('name' => 'WzPageThree',
                  'location' => 'ESERV/MAIN/WizardBundle/'),
            array('name' => 'WzPageTwo',
                  'location' => 'ESERV/MAIN/WizardBundle/'),
            
            array('name' => 'EservRole',
                  'location' => 'Security/EservRoleBundle/'),            
            
            array('name' => 'MtlSession',
                  'location' => 'Security/SessionBundle/'),
            
            array('name' => 'AltLanguage',
                  'location' => 'ESERV/MAIN/HelpersBundle/'),
            array('name' => 'AltLanguageEntity',
                  'location' => 'ESERV/MAIN/HelpersBundle/'),
            array('name' => 'AltLanguageEquivalent',
                  'location' => 'ESERV/MAIN/HelpersBundle/'),
            array('name' => 'AltLanguageReltypeEquiv',
                  'location' => 'ESERV/MAIN/HelpersBundle/'),
            array('name' => 'AltLanguageMmhelpEquiv',
                  'location' => 'ESERV/MAIN/HelpersBundle/'),
            array('name' => 'AppText',
                  'location' => 'ESERV/MAIN/HelpersBundle/'),
            array('name' => 'AltLanguageAppText',
                  'location' => 'ESERV/MAIN/HelpersBundle/'),
            
            array('name' => 'Member',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'MembershipOrg',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'EmploymentDetail',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'EmploymentDetailHist',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'MemberStatus',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'MemberRate',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'ContRateMaster',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'ContRate',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'Employer',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'Workplace',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'Branch',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'MemberStatusReason',
                  'location' => 'ESERV/MAIN/MembershipBundle/'), 
            array('name' => 'MemberHist',
                  'location' => 'ESERV/MAIN/MembershipBundle/'), 
            array('name' => 'MemberDisciplinary',
                  'location' => 'ESERV/MAIN/MembershipBundle/'), 
            array('name' => 'MemberDisciplinaryType',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            array('name' => 'MemberSubjectTaught',
                  'location' => 'ESERV/MAIN/MembershipBundle/'), 
            array('name' => 'MemberSubject',
                  'location' => 'ESERV/MAIN/MembershipBundle/'),
            
            array('name' => 'ClientEntity',
                  'location' => 'ESERV/MAIN/AdministrationBundle/Components/ClientAdministrationBundle/'),
            array('name' => 'ClientField',
                  'location' => 'ESERV/MAIN/AdministrationBundle/Components/ClientAdministrationBundle/'),
            array('name' => 'ClientFieldSelectOption',
                  'location' => 'ESERV/MAIN/AdministrationBundle/Components/ClientAdministrationBundle/'),
            array('name' => 'ClientTable',
                  'location' => 'ESERV/MAIN/AdministrationBundle/Components/ClientAdministrationBundle/'),
            array('name' => 'ClientTableMap',
                  'location' => 'ESERV/MAIN/AdministrationBundle/Components/ClientAdministrationBundle/'),
            
            array('name' => 'GtcwMain',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwQtsMain',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwQtsRange',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwQtsStatus',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwSuitMain',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMemIndStatus',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMemIndRoute',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMemIndTerm',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMemIndSubject',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMemMepStatus',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMemMepDetail',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMemMepModule',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMemMepPayment',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMemEpd',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMemEpdCat',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMentor',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMentorTeacher',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMentorEmpHist',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwMentorPayment',
                  'location' => 'GTCW/GTCWBundle/'),            
            array('name' => 'GtcwInfTableInfo',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwInfDiskData',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwInfDataQts',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwInfDataError',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwResultFile',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwRegistrationHistory',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwExportBatch',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwPersonNameHistory',
                  'location' => 'GTCW/GTCWBundle/'),
            array('name' => 'GtcwSearch',
                  'location' => 'GTCW/GTCWBundle/'),
			
			array('name' => 'Subject',
                  'location' => 'ESERV/MAIN/QualificationBundle/'),
            array('name' => 'Qualification',
                  'location' => 'ESERV/MAIN/QualificationBundle/'),
            array('name' => 'Establishment',
                  'location' => 'ESERV/MAIN/QualificationBundle/'),
            array('name' => 'ContactQualification',
                  'location' => 'ESERV/MAIN/QualificationBundle/'),
            array('name' => 'ContactQualificationSubj',
                  'location' => 'ESERV/MAIN/QualificationBundle/'),
            
            array('name' => 'DocumentMaster',
                  'location' => 'ESERV/MAIN/DocumentBundle/'),
            array('name' => 'DocumentMasterVersion',
                  'location' => 'ESERV/MAIN/DocumentBundle/'),
            array('name' => 'DocumentMasterAccess',
                  'location' => 'ESERV/MAIN/DocumentBundle/'),
            array('name' => 'ContactDocumentSubscription',
                  'location' => 'ESERV/MAIN/DocumentBundle/'),
            array('name' => 'ContactDoc',
                  'location' => 'ESERV/MAIN/DocumentBundle/'),
            array('name' => 'ContactDocHist',
                  'location' => 'ESERV/MAIN/DocumentBundle/'),
            array('name' => 'ContactDocStore',
                  'location' => 'ESERV/MAIN/DocumentBundle/'),
            array('name' => 'ContactUploadedDocStore',
                  'location' => 'ESERV/MAIN/DocumentBundle/'),
            array('name' => 'ContactUploadedDoc',
                  'location' => 'ESERV/MAIN/DocumentBundle/'),
            array('name' => 'ContactDocAccess',
                  'location' => 'ESERV/MAIN/DocumentBundle/'),
            
            array('name' => 'CpdStatus',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'CpdStatusDetail',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'ContactCpdStatus',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'ContactCpdStatusDetail',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'ContactCpdStatusHist',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'ContactCpdStatusDetailHist',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'CpdAct',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'CpdActType',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'CpdActCategory',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'CpdActTypeDetail',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'ContactCpdAct',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'ContactCpdActDet',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'ContactCpdDocLib',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'ContactCpdActDoc',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'CpdActCodeControl',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'CpdActCodeVal',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            array('name' => 'ContactCpdActCode',
                  'location' => 'ESERV/MAIN/CpdBundle/'),
            
//            array('name' => 'FosUser',
//                  'location' => 'Security/UserBundle/'),
//            array('name' => 'FosGroup',
//                  'location' => 'Security/UserBundle/'),
//            array('name' => 'FosUserGroup',
//                  'location' => 'Security/UserBundle/'), fk_ccpdsd_cocshi fk_ccpdsd_cpstde
            
        );        
    }

    public function getFileNamesArray()
    {
        return $this->file_names_array;
    }   
}
