<?php

namespace ESERV\MAIN\QualificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
        # namespace GTCW\GTCWBundle\Entity;
namespace ESERV\MAIN\QualificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

class QualMandRepository extends EntityRepository {

    public function getQualMandForRegistrant($qual_id, $membership_org_id) {        

        $query = $this->createQueryBuilder('qm')
                ->innerJoin('qm.qualMandControl', 'qmc')
                ->where('qmc.membershipOrg = :membership_org_id')
                ->setParameter('membership_org_id', $membership_org_id)
                ->andWhere('qm.qualification = :qual_id')
                ->setParameter('qual_id', $qual_id)
                ->andWhere('qm.qualMandValue = :qual_mand_value')
                 ->setParameter('qual_mand_value', 'Y')
                ->getQuery();

        $result = $query->getOneOrNullResult();
        return $result;
    }

}
