<?php

/*
  This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
  information. Thanks.
 */

namespace ESERV\MAIN\QualificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends EntityRepository {

    public function getAllSubjects() {        

        $em = $this->getEntityManager()->createQueryBuilder();
        $subjects = $em->select('s.id, s.code, s.name')
                ->from('ESERVMAINQualificationBundle:Subject', 's')
                ->orderBy('s.name', 'ASC')
                ->getQuery()
                ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        $subject_array = array();
        foreach ($subjects as $a) {
            $subject_array[$a['id']] = $a['name'].'('.$a['code'].')';
        }

        return $subject_array;
    }

}
