<?php

namespace ESERV\MAIN\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactDocAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactDocAccessRepository extends EntityRepository
{
    public function getByContact($contact) {
        $return_data = FALSE;
        try {
            $query = $this->createQueryBuilder('a')
                          ->innerJoin('a.contactDoc', 'd')
                          ->innerJoin('d.conDocSub', 's')
                          ->where('s.contact = :contact_rec')
                          ->setParameter('contact_rec', $contact)
                          ->getQuery();
            $return_data = $query->getResult();
        } catch (\Exception $ex) {
            $return_data = FALSE;
            echo $ex->getMessage();
        }
        
        return $return_data;
    } #getByContact
}
