ESERV\MAIN\ContactBundle\Components\ContactDetailsBundle\Entity\EservVAddress:
    type: entity
    repositoryClass: ESERV\MAIN\ContactBundle\Components\ContactDetailsBundle\Entity\EservVAddressRepository    
    table: eserv_v_address

    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: IDENTITY
    fields:
        contactId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: contact_id
        contactDisplayName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: contact_display_name
        addressTypeId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: address_type_id
        addressTypeCode:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: address_type_code
        addressTypeName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: address_type_name
        countryId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: country_id
        countryCode:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
            column: country_code
        countryDescription:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: country_description
        addressLine1:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: address_line1
        addressLine2:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: address_line2
        addressLine3:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: address_line3
        town:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: town
        county:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: county
        postcode:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
            column: postcode
        startDate:
            type: datetime
            nullable: false
            comment: ''
            column: start_date
        primaryRecord:
            type: string
            nullable: false
            length: 1
            fixed: false
            default: N
            column: primary_record
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
        createdBy:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: created_by