<?php

namespace ESERV\MAIN\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactDocumentSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactDocumentSubscriptionRepository extends EntityRepository
{
    const REPOSITORY_NAME = 'ContactDocumentSubscriptionRepository';
    
    public function getByContactId($contact) {
        $con_doc_sub = FALSE;
        
        try {
            $query = $this->createQueryBuilder('c');
                     
            if ($contact instanceof \ESERV\MAIN\ContactBundle\Entity\Contact) {
                $query->where('c.contact = :contactRec')
                      ->setParameter('contactRec', $contact);
            } else {
                $query->innerJoin('c.contact', 'a')
                      ->where('a.id = :contact_id')
                      ->setParameter('contact_id', $contact);
            }
            $con_doc_sub = $query->getQuery()->getOneOrNullResult();
        } catch (\Exception $ex) {
            $con_doc_sub = FALSE;
        }
        
        return $con_doc_sub;
    } #getByContactId
            
}
