ESERV\MAIN\ActivityBundle\Entity\ActivityComment: 
    type: entity
    repositoryClass: ESERV\MAIN\ActivityBundle\Entity\ActivityCommentRepository
    table: activity_comment
    indexes:
        fk_actcom_act_idx:
            columns:
                - activity_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        actNote:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: act_note
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        activity:
            targetEntity: ESERV\MAIN\ActivityBundle\Entity\Activity
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                activity_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
