ESERV\MAIN\ActivityBundle\Entity\ActivityAssignment: 
    type: entity
    repositoryClass: ESERV\MAIN\ActivityBundle\Entity\ActivityAssignmentRepository
    table: activity_assignment
    indexes:
        fk_actassig_act_idx:
            columns:
                - activity_id
        fk_actassig_con_idx:
            columns:
                - contact_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        activity:
            targetEntity: ESERV\MAIN\ActivityBundle\Entity\Activity
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                activity_id:
                    referencedColumnName: id
            orphanRemoval: false
        contact:
            targetEntity: ESERV\MAIN\ContactBundle\Entity\Contact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
