<?php

namespace WEBLOGS\CORE\MAIN\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MmUserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MmUserProfileRepository extends EntityRepository
{
}
