-- MM_USER_SETTING_ORG

CREATE TABLE "MILLER_WEB_DEMO"."MM_USER_SETTING_ORG" 
 (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
      "MM_USER_SETTING_FOS_ID" NUMBER(10,0) NOT NULL ENABLE, 
      "CUSTOMER_CODE" VARCHAR2(20 BYTE), 
      "CREATED_AT" DATE, 
      "UPDATED_AT" DATE, 
      "CREATED_BY" NUMBER(10,0), 
      "UPDATED_BY" NUMBER(10,0), 
       CONSTRAINT "MM_USER_SETTING_ORG_PK" PRIMARY KEY ("ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_SMALL"  ENABLE
 ) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_SMALL" ;

ALTER TABLE mm_user_setting_org
    ADD CONSTRAINT fk_mmusor_mmusfo 
        FOREIGN KEY (mm_user_setting_fos_id)
        REFERENCES mm_user_setting_fos (id);

-- USER_COMMS_DET

CREATE TABLE "MILLER_WEB_DEMO"."USER_COMMS_DET" 
 (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
      "MM_USER_SETTING_ORG_ID" NUMBER(10,0) NOT NULL ENABLE, 
      "EMAIL_ADDRESS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
       CONSTRAINT "USER_COMMS_DET_PK" PRIMARY KEY ("ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_SMALL"  ENABLE
 ) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_SMALL" ;

ALTER TABLE user_comms_det
    ADD CONSTRAINT fk_uscode_mmusor 
        FOREIGN KEY (mm_user_setting_org_id)
        REFERENCES mm_user_setting_org (id);

-- PERSON_WEB
  CREATE TABLE "MILLER_WEB_DEMO"."PERSON_WEB" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(10 BYTE), 
	"FORENAME" VARCHAR2(100 BYTE), 
	"SURNAME" VARCHAR2(100 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"CREATED_AT" DATE, 
	"CREATED_BY" NUMBER(11,0), 
	"UPDATED_AT" DATE, 
	"UPDATED_BY" NUMBER(11,0), 
	 CONSTRAINT "PERSON_WEB_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_SMALL" ;

--

Insert into MILLER_WEB_DEMO.FOS_GROUP (ID,NAME) values (4,'MTL');
Insert into MILLER_WEB_DEMO.FOS_GROUP (ID,NAME) values (5,'CUSTOMER');

Insert into MILLER_WEB_DEMO.FOS_USER (ID,USERNAME,USERNAME_CANONICAL,EMAIL,EMAIL_CANONICAL,ENABLED,SALT,PASSWORD,LAST_LOGIN,LOCKED,EXPIRED,EXPIRES_AT,CONFIRMATION_TOKEN,PASSWORD_REQUESTED_AT, ROLES, CREDENTIALS_EXPIRED,CREDENTIALS_EXPIRE_AT) values (2,'anjanamtl','anjanamtl','anjana@millertech.co.uk','anjana@millertech.co.uk',1,'f8zstia9uw0gww4o40owsg8ws0gogok','20obqJmT+ihF2tlIn8TYn8qiN9QEFFP24wBrjjUwA+4HfDKlYBLwhx1hftZhpO0YykgX6OPwX0hrwk3M+EnT5w==',null,0,0,null,null,null,'a:0:{}',0,null);
Insert into MILLER_WEB_DEMO.FOS_USER (ID,USERNAME,USERNAME_CANONICAL,EMAIL,EMAIL_CANONICAL,ENABLED,SALT,PASSWORD,LAST_LOGIN,LOCKED,EXPIRED,EXPIRES_AT,CONFIRMATION_TOKEN,PASSWORD_REQUESTED_AT, ROLES,CREDENTIALS_EXPIRED,CREDENTIALS_EXPIRE_AT) values (3,'anjanaunison','anjanaunison','anjana@millertech.co.uk','anjana@millertech.co.uk',1,'f8zstia9uw0gww4o40owsg8ws0gogok','20obqJmT+ihF2tlIn8TYn8qiN9QEFFP24wBrjjUwA+4HfDKlYBLwhx1hftZhpO0YykgX6OPwX0hrwk3M+EnT5w==',null,0,0,null,null,null,'a:0:{}',0,null);
Insert into MILLER_WEB_DEMO.FOS_USER (ID,USERNAME,USERNAME_CANONICAL,EMAIL,EMAIL_CANONICAL,ENABLED,SALT,PASSWORD,LAST_LOGIN,LOCKED,EXPIRED,EXPIRES_AT,CONFIRMATION_TOKEN,PASSWORD_REQUESTED_AT, ROLES, CREDENTIALS_EXPIRED,CREDENTIALS_EXPIRE_AT) values (4,'anjanainto','anjanainto','anjana@millertech.co.uk','anjana@millertech.co.uk',1,'f8zstia9uw0gww4o40owsg8ws0gogok','20obqJmT+ihF2tlIn8TYn8qiN9QEFFP24wBrjjUwA+4HfDKlYBLwhx1hftZhpO0YykgX6OPwX0hrwk3M+EnT5w==',null,0,0,null,null,null,'a:0:{}',0,null);

Insert into MILLER_WEB_DEMO.FOS_USER_GROUP (USER_ID,GROUP_ID) values (2,4);
Insert into MILLER_WEB_DEMO.FOS_USER_GROUP (USER_ID,GROUP_ID) values (3,5);
Insert into MILLER_WEB_DEMO.FOS_USER_GROUP (USER_ID,GROUP_ID) values (4,5);

Insert into MILLER.PERSONS (PERSON_ID,NATIONAL_INSURANCE_NO,TITLE,INITIALS,FORENAME,SURNAME,SUFFIX,SEX,DATE_OF_BIRTH,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,TOWN,COUNTY,POSTCODE,MAILSORTCODE,HOME_PHONE_NO,MOBILE_NO,FAX_NO,PER_STATUS_CODE,PER_STATUS_DATE,PER_USER_ID,PER_DATE_LAST_UPDATED,MAIN_PERSON_ID,TAX_CODE,JOIN_DATE,PER_JOB_TITLE,STAFF_RECORD,PER_REGISTRATION_NO,PER_PROJECT_MGR,PER_LINE_MGR) values ('999',null,'MR','APS','Anjana','Silva',null,'M',to_date('01-SEP-88','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into MILLER.PERSONS (PERSON_ID,NATIONAL_INSURANCE_NO,TITLE,INITIALS,FORENAME,SURNAME,SUFFIX,SEX,DATE_OF_BIRTH,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,TOWN,COUNTY,POSTCODE,MAILSORTCODE,HOME_PHONE_NO,MOBILE_NO,FAX_NO,PER_STATUS_CODE,PER_STATUS_DATE,PER_USER_ID,PER_DATE_LAST_UPDATED,MAIN_PERSON_ID,TAX_CODE,JOIN_DATE,PER_JOB_TITLE,STAFF_RECORD,PER_REGISTRATION_NO,PER_PROJECT_MGR,PER_LINE_MGR) values ('998',null,'MR','R','Ramesh','Tripathi',null,'M',to_date('01-JUN-86','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into MILLER.PERSONS (PERSON_ID,NATIONAL_INSURANCE_NO,TITLE,INITIALS,FORENAME,SURNAME,SUFFIX,SEX,DATE_OF_BIRTH,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,TOWN,COUNTY,POSTCODE,MAILSORTCODE,HOME_PHONE_NO,MOBILE_NO,FAX_NO,PER_STATUS_CODE,PER_STATUS_DATE,PER_USER_ID,PER_DATE_LAST_UPDATED,MAIN_PERSON_ID,TAX_CODE,JOIN_DATE,PER_JOB_TITLE,STAFF_RECORD,PER_REGISTRATION_NO,PER_PROJECT_MGR,PER_LINE_MGR) values ('997',null,'MR','SJ','Simon','Till',null,'M',to_date('01-MAR-84','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into MILLER_WEB_DEMO.MM_USER_SETTING_FOS (ID,MM_USER_PROFILE_ID,AUTO_SAVE,LANGUAGE,LAST_VIEWED_NEWS,LAYOUT_STATE,MENU_STATE,STATUS_DATE,THEME,THEME_FONT_SIZE,THEME_WIDTH,CREATED_AT,UPDATED_AT,CREATED_BY,UPDATED_BY,FOS_USER_ID,PERSON_ID) values (2,1,'10','en',to_date('20-FEB-05','DD-MON-RR'),'Test Layour State','grid_menu',to_date('20-FEB-05','DD-MON-RR'),'default-DEFAULT',12,'720',null,null,null,null,2,'999');
Insert into MILLER_WEB_DEMO.MM_USER_SETTING_FOS (ID,MM_USER_PROFILE_ID,AUTO_SAVE,LANGUAGE,LAST_VIEWED_NEWS,LAYOUT_STATE,MENU_STATE,STATUS_DATE,THEME,THEME_FONT_SIZE,THEME_WIDTH,CREATED_AT,UPDATED_AT,CREATED_BY,UPDATED_BY,FOS_USER_ID,PERSON_ID) values (3,1,'10','en',to_date('20-FEB-05','DD-MON-RR'),'Test Layour State','grid_menu',to_date('20-FEB-05','DD-MON-RR'),'default-DEFAULT',12,'720',null,null,null,null,3,'998');
Insert into MILLER_WEB_DEMO.MM_USER_SETTING_FOS (ID,MM_USER_PROFILE_ID,AUTO_SAVE,LANGUAGE,LAST_VIEWED_NEWS,LAYOUT_STATE,MENU_STATE,STATUS_DATE,THEME,THEME_FONT_SIZE,THEME_WIDTH,CREATED_AT,UPDATED_AT,CREATED_BY,UPDATED_BY,FOS_USER_ID,PERSON_ID) values (4,1,'10','en',to_date('20-FEB-05','DD-MON-RR'),'Test Layour State','grid_menu',to_date('20-FEB-05','DD-MON-RR'),'default-DEFAULT',12,'720',null,null,null,null,4,'997');

Insert into MILLER_WEB_DEMO.MM_USER_SETTING_ORG (ID,MM_USER_SETTING_FOS_ID,CUSTOMER_CODE,CREATED_AT,UPDATED_AT,CREATED_BY,UPDATED_BY) values (1,3,'UNIUAT',null,null,null,null);
Insert into MILLER_WEB_DEMO.MM_USER_SETTING_ORG (ID,MM_USER_SETTING_FOS_ID,CUSTOMER_CODE,CREATED_AT,UPDATED_AT,CREATED_BY,UPDATED_BY) values (2,3,'UNISON',null,null,null,null);
Insert into MILLER_WEB_DEMO.MM_USER_SETTING_ORG (ID,MM_USER_SETTING_FOS_ID,CUSTOMER_CODE,CREATED_AT,UPDATED_AT,CREATED_BY,UPDATED_BY) values (3,3,'UNINEP',null,null,null,null);
Insert into MILLER_WEB_DEMO.MM_USER_SETTING_ORG (ID,MM_USER_SETTING_FOS_ID,CUSTOMER_CODE,CREATED_AT,UPDATED_AT,CREATED_BY,UPDATED_BY) values (4,3,'UNIFIN',null,null,null,null);

Insert into MILLER_WEB_DEMO.MM_USER_SETTING_ORG (ID,MM_USER_SETTING_FOS_ID,CUSTOMER_CODE,CREATED_AT,UPDATED_AT,CREATED_BY,UPDATED_BY) values (5,4,'INTO',null,null,null,null);