Security\UserBundle\Entity\Email:
    type: entity
    repositoryClass: Security\UserBundle\Entity\EmailRepository
    table: email    
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email_address:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: email_address
        person_id:
            type: integer
            nullable: false
            unsigned: false
            column: person_id
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by    
    lifecycleCallbacks: {  }
