<?php

namespace ESERV\MAIN\TemplateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EservVCurrTemplateVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EservVCurrTemplateVersionRepository extends EntityRepository
{
}
