<?php
            
/*
    This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
    information. Thanks.
*/

namespace ESERV\MAIN\CpdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactCpdStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactCpdStatusRepository extends EntityRepository
{   
    
    public function getContactCpdStatusCurrent($contactId, $cpdStatus) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $ccs = $qb->select('ccs.id as contactCpdStatusId', 'cs.id as cpdStatusId')
                ->from('ESERVMAINCpdBundle:ContactCpdStatus', 'ccs')                
                ->leftJoin('ccs.cpdStatus', 'cs')
                ->leftJoin('ESERVMAINCpdBundle:ContactCpdStatusHist', 'ccsh','with','ccsh.contactCpdStatus = ccs.id')
                ->where('ccsh.id is NULL')
                ->andWhere('ccs.cpdStatus = :cst')
                ->setParameter('cst', $cpdStatus)
                ->andWhere('ccs.contact = :c')
                ->setParameter('c', $contactId)
                ->getQuery()
                ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        
        $ccsArray = array();
        foreach ($ccs as $value) {
            return $value;
        }        
        return $ccsArray;        
    }   
    
    
}