WEBLOGS\MAIN\MTL\MyLogsBundle\Entity\Customers:
    type: entity
    table: customers
#    id:
#        dtindex:
#            type: string
#            nullable: false
#            length: 10
#            fixed: false
#            id: true
#            generator:
#            strategy: IDENTITY
    fields:
        customer_id:
            type: string
            nullable: false
            length: 100
            id: true
            fixed: false
            column: customer_id
        name:
            type: string
            nullable: false
            length: 300
            fixed: false
            column: name
        
    lifecycleCallbacks: {  }
