WEBLOGS\MAIN\MTL\MyLogsBundle\Entity\VWwvLogAction:
    type: entity
    table: v_wwv_log_action
#    id:
#        dtindex:
#            type: string
#            nullable: false
#            length: 10
#            fixed: false
#            id: true
#            generator:
#            strategy: IDENTITY
    fields:
              
         
        ACTION_ID:
            type: string
            nullable: false
            length: 100
            fixed: false
            id: true
            column: ACTION_ID
        DESCRIPTION:
            type: string
            nullable: false
            length: 300
            fixed: false
            column: DESCRIPTION
        
        
    lifecycleCallbacks: {  }
