<?php

namespace ESERV\MAIN\SystemConfigBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SystemIconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemIconRepository extends EntityRepository
{
}
