ESERV\MAIN\CommunicationsBundle\Entity\EmailMergingLookupArchive: 
    type: entity
    repositoryClass: ESERV\MAIN\CommunicationsBundle\Entity\EmailMergingLookupArchiveRepository
    table: email_merging_lookup_archive
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entityName:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: entity_name
        entityId:
            type: integer
            nullable: false
            unsigned: false
            column: entity_id
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    lifecycleCallbacks: {  }
