ESERV\MAIN\MediaBundle\Entity\MediaType: 
    type: entity
    repositoryClass: ESERV\MAIN\MediaBundle\Entity\MediaTypeRepository
    table: media_type
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        mimeType:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: mime_type
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    lifecycleCallbacks: {  }
