ESERV\MAIN\HistoryBundle\Entity\MtlDeletedRecord:
    type: entity
    repositoryClass: ESERV\MAIN\HistoryBundle\Entity\MtlDeletedRecordRepository
    table: mtl_deleted_record
    indexes:
        fk_mtldel_contact_idx:
            columns:
                - contact_id
        fk_mtldel_entnam_idx:
            columns:
                - entity_name
        fk_mtldel_entid_idx:
            columns:
                - entity_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entityId:
            type: integer
            nullable: false
            unsigned: false
            column: entity_id
        entityName:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: entity_name
        columnsAndValues:
            type: text
            nullable: true
            length: 65535
            fixed: false
            column: columns_and_values
        deletedFrom:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: deleted_from
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        contact:
            targetEntity: ESERV\MAIN\ContactBundle\Entity\Contact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
