ESERV\MAIN\HistoryBundle\Entity\PageRecordLastViewed: 
    type: entity
    repositoryClass: ESERV\MAIN\HistoryBundle\Entity\PageRecordLastViewedRepository
    table: page_record_last_viewed
    indexes:
        fk_page_record_last_viewed_fos_user1_idx:
            columns:
                - fos_user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pageName:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: page_name
        entityName:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: entity_name
        entityId:
            type: integer
            nullable: false
            unsigned: false
            column: entity_id
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        fosUser:
            targetEntity: ESERV\MAIN\SecurityBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fos_user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
