<?php

/*
  This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
  information. Thanks.
 */

namespace ESERV\MAIN\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository {
    
    public function getById($id, $col = 'ALL') {        
        if ($col === 'ALL') {
            $query = $this->createQueryBuilder('c')
                          ->where('c.id = :contact_id')
                          ->setParameter('contact_id', $id)
                          ->getQuery();
            $result = $query->getOneOrNullResult();
        } else {
            if (is_array($col)) {
                $col_arr = $col;
            } else {
                $col_arr = array($col);
            }
            $select_col = '';
            foreach($col_arr as $key => $value) {
              $select_col = $select_col . 'c.' . $value . ',';
            }
            $select_col = rtrim($select_col, ',');
            $query = $this->createQueryBuilder('c')
                          ->select($select_col)
                          ->where('c.id = :contact_id')
                          ->setParameter('contact_id', $id)
                          ->getQuery();
            $result = $query->getOneOrNullResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        }        
        
        return $result;
    } #getById
/*
    public function getBySystemCodeTypeAndCode($system_code_type, $code, $col = 'ALL') {        
        if ($col === 'ALL') {
            $query = $this->createQueryBuilder('s')
                          ->leftJoin('s.systemCodeType', 't')
                          ->where('t.code = :system_code_type')
                          ->andWhere('s.code = :code')
                          ->setParameter('system_code_type', $system_code_type)
                          ->setParameter('code', $code)
                          ->getQuery();
            $result = $query->getOneOrNullResult();
        } else {
            if (is_array($col)) {
                $col_arr = $col;
            } else {
                $col_arr = array($col);
            }
            $select_col = '';
            foreach($col_arr as $key => $value) {
              $select_col = $select_col . 's.' . $value . ',';
            }
            $select_col = rtrim($select_col, ',');
            $query = $this->createQueryBuilder('s')
                          ->select($select_col)
                          ->leftJoin('s.systemCodeType', 't')
                          ->where('t.code = :system_code_type')
                          ->andWhere('s.code = :code')
                          ->setParameter('system_code_type', $system_code_type)
                          ->setParameter('code', $code)
                          ->getQuery();
            $result = $query->getOneOrNullResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        }        
        
        return $result;
    }
*/
}
