<?php

namespace ESERV\MAIN\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EservVRelationshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EservVRelationshipRepository extends EntityRepository
{
}
