<?php

/*
  This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
  information. Thanks.
 */

namespace ESERV\MAIN\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository {

    public function getPersonInfoByContactIds($contactIds) {
        $result = array();
        try {
            $result = $this->createQueryBuilder('p')
//                                ->select('p.referenceNo, p.initials, p.firstName, p.lastName, p.dateOfBirth, p.gender')
                    ->leftJoin('p.contact', 'c')
                    ->where('c.id IN (:cids)')
                    ->setParameter('cids', $contactIds)
                    ->getQuery()
                    ->execute()
//                                ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY)
            ;
        } catch (Exception $ex) {
            
        }

        return $result;
    }

//Doctrine does something weird with the join, so had to create a new view - eserv_v_contact_person
//    public function getDataBySubQuery($sub_query, $cols = 'ALL') {
//        $qb = $this->getEntityManager()->createQueryBuilder();
//        $sql = $qb->select('p')
//                  ->from('ESERVMAINContactBundle:Person', 'p')
//                  ->innerJoin('ESERVMAINContactBundle:Contact', 'c')
//                  ->where($qb->expr()->in('c.id', $sub_query))
//                  ->orderBy('p.lastName, p.firstName')
//                  ->getQuery();
//        var_dump($sql->getDQL()); die;
//        $result = $sql->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
//        
//        return $result;        
//    } #getDataBySubQuery end

}
