<?php

/*
    This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
    information. Thanks.
*/

namespace ESERV\MAIN\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationshipRepository extends EntityRepository
{
/*
    public function insertRelationship($em, $contact_a, $contact_b, $relationship_type, $start_date = NULL, $end_date = NULL) {
        try {
            if ($contact_a instanceof \ESERV\MAIN\ContactBundle\Entity\RelationshipType) {
                $insert_rel_type = $relationship_type;
            } else {
                $insert_rel_type = $this->em->getRepository('ESERVMAINContactBundle:RelationshipType')->findOneBy(array('id' => $relationship_type));
            }
            if ($relationship_type instanceof \ESERV\MAIN\ContactBundle\Entity\Relationship\RelationshipType) {
                $insert_rel_type = $relationship_type;
            } else {
                $insert_rel_type = $this->em->getRepository('ESERVMAINContactBundle:RelationshipType')->findOneBy(array('id' => $relationship_type));
            }
            if ($start_date == NULL) {
                $insert_start_date = new \DateTime();
            }
            if ($end_date == NULL) {
                $insert_end_date = NULL;
            }
            $new_rel = new \ESERV\MAIN\ContactBundle\Entity\Relationship();
            $new_rel->setContactA();
            $new_rel->setContactB($user_contact);
            $new_rel->setRelationshipType($insert_rel_type);
            $new_rel->setStartDate($insert_start_date);
            $new_rel->setEndDate($insert_end_date);
            $em->persist($new_rel);
            $em->flush();
        } catch (\Exception $e) {

        }

        return $rel;
    }
*/
}