ESERV\MAIN\AdministrationBundle\Components\ClientAdministrationBundle\Entity\ClientEntity: 
    type: entity
    repositoryClass: ESERV\MAIN\AdministrationBundle\Components\ClientAdministrationBundle\Entity\ClientEntityRepository
    table: client_entity
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entityName:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: entity_name
        entityDescription:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: entity_description
        subEntityName:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: sub_entity_name
        subEntityDescription:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: sub_entity_description
        entityIdTable:
            type: string
            nullable: true
            length: 100
            fixed: false
            column: entity_id_table
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    lifecycleCallbacks: {  }
