ESERV\MAIN\AdministrationBundle\Components\ClientAdministrationBundle\Entity\ClientFieldSelectOption: 
    type: entity
    repositoryClass: ESERV\MAIN\AdministrationBundle\Components\ClientAdministrationBundle\Entity\ClientFieldSelectOptionRepository
    table: client_field_select_option
    indexes:
        fk1_client_field_id1_idx:
            columns:
                - client_field_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: false
            length: 255
            fixed: false
        value:
            type: string
            nullable: false
            length: 255
            fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
    manyToOne:
        clientField:
            targetEntity: ESERV\MAIN\AdministrationBundle\Components\ClientAdministrationBundle\Entity\ClientField
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_field_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
