<?php
            
/*
    This file has been generated using MTL ESERV:BUILD command. Contact Anjana on anjana@millertech.co.uk for more
    information. Thanks.
*/

namespace ESERV\MAIN\CpdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactCpdStatusDetailHistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactCpdStatusDetailHistRepository extends EntityRepository
{
    
    public function ifStatusHistoryHasOtherDetails($statusHistoryId, $statusDetailHistoryId) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $result = $qb->select('sdh')
                ->from('ESERVMAINCpdBundle:ContactCpdStatusDetailHist', 'sdh')
                ->leftJoin('sdh.contactCpdStatusHist', 'sh')
                ->where('sh.id = :shId')
                ->setParameter('shId', $statusHistoryId)
                ->andWhere('sdh.id NOT IN (:sdhId)')
                ->setParameter('sdhId', $statusDetailHistoryId)
                ->getQuery()
                ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        if(count($result)>0){
            return true;
        } else {
            return false;
        }
    }

}